services:
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: API/Dockerfile
  #   ports:
  #     - "7001:8080" # Maps container port 5000 to host port 5000
  #   networks:
  #     - localdev    

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=Senha@123"
    ports:
      - "1433:1433"
    hostname: mssql
    container_name: mssql
    volumes:
      - "mssql-azuresql-edge-data:/var/opt/mssql"

volumes:
  mssql-azuresql-edge-data:
    
networks:
  localdev:
    # Specify driver options
    driver: bridge