@API_HostAddress = http://localhost:5000/api

### GET PRODUCTS
GET {{API_HostAddress}}/product
Accept: application/json
Content-Type: application/json
    
###

### GET PRODUCTS BY ID
GET {{API_HostAddress}}/product/1
Accept: application/json
Content-Type: application/json

###

